language:
  - ruby
  - node_js

rvm: 2.4.1

node_js: 8

cache:
  bundler: true
  yarn: true
  directories:
    - client/node_modules

install:
  - ./bin/setup

script:
  - bundle exec rake test
  - cd client && yarn test
